name: Deploy SKV

on:
  push:
    branches:
      - master

concurrency:
  group: skv-production
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to Raspberry Pi

    runs-on:
      - self-hosted
      - Linux
      - ARM64

    timeout-minutes: 30

    steps:
      - name: Deploy master
        run: |
          bash /opt/skv_web/deploy/deploy.sh